/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  NewAccount: () => import('#controllers/new_account_controller'),
  QuickView: () => import('#controllers/quick_view_controller'),
  Session: () => import('#controllers/session_controller'),
  Spotify: () => import('#controllers/spotify_controller'),
}
